Capstone/resturant/core/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views
from django.urls import path 


from order.views import add_to_order, order, hx_menu_order, update_order
from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name="browser"),
    path('order/', order, name='order'),
    path('add_to_order/<int:meal_id>/', add_to_order, name='add_to_order'),
    path('update_order/<int:meal_id>/<str:action>/', update_order, name='update_order'),
    path('hx_menu_order/', hx_menu_order, name="hx_menu_order"),
    path('contacts/', views.contact, name='contacts'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', views.logout_req, name='logout')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Capstone/resturant/resturant/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls', namespace='test')),
    path('admin/', admin.site.urls),
]

Capstone/resturant/meal/models.py
from django.db import models

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=225)
    slug = models.SlugField(null=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name



class Meal(models.Model):
    category = models.ForeignKey(Category, related_name='meals', on_delete=models.CASCADE, default=False, null=True)
    name = models.CharField(max_length=225)
    slug = models.SlugField(null=True)
    price = models.FloatField(null=True)
    image = models.ImageField(upload_to='meal_images', blank=True, null=True)
    quantity = models.IntegerField(default=0)
    
    def __str__(self):
        return self.name

Capstone/resturant/order/models.py
from django.db import models

# Create your models here.

Capstone/resturant/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    pass

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
        

Capstone/resturant/core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout

from meal.models import Category, Meal

from .forms import SignupForm

# Create your views here.

def index(request):
    category = request.GET.get('category')
    
    if category == None:
        meals = Meal.objects.all()
    else:
        meals = Meal.objects.filter(category__name=category)
    
    categories = Category.objects.all()
    return render(request, 'core/browser.html', {
        'categories': categories,
        'meals': meals,
    })

def contact(request):
    return render(request, 'core/contact.html')

def signup(request):
    if request.method =='POST':
        form = SignupForm(request.POST)
        
        if form.is_valid():
            form.save()
            
            return redirect('/login/')
    form = SignupForm()
    
    return render(request, 'core/signup.html', {
        'form': form,
    })
    
def logout_req(request):
    logout(request)
    return redirect("/")

Capstone/resturant/meal/views.py
from django.shortcuts import render

# Create your views here.

Capstone/resturant/order/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from .order import Order
from meal.models import Meal

# Create your views here.

def add_to_order(request, meal_id):
    order = Order(request)
    order.add(meal_id)
    
    return render(request, 'order/menu_order.html')

def update_order(request, meal_id, action):
    order = Order(request)
    
    if action == 'increment':   
        order.add(meal_id, 1, True)
    else:
        order.add(meal_id, -1, True)
        
    meal = Meal.objects.get(pk=meal_id)
    
    item = {
        'meal': {
            'id': meal.id,
            'name': meal.name,
            'image': meal.image,
            'price': meal.price,
        },
        'total_price': meal.quantity * meal.price,
        'quantity': meal.quantity,
    }
    
    response = render(request, 'order/partials/meal_item.html', {'item': item})
    response['HX-Trigger'] = 'update-menu-order'
    return response

@login_required
def order(request):
    return render(request, 'order/order.html')

def hx_menu_order(request):
    return render(request, 'order/menu_order.html')

Capstone/resturant/core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://unpkg.com/htmx.org@1.8.5"></script>
    <script src="https://cdn.tailwindcss.com"></script>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <nav class="flex fixed min-w-full justify-center items-center gap-20 h-10 max-h-full bg-zinc-900 shadow-lg text-white">
        <h1 class="">PortsInMeals</h1>
        <ul class="flex justify-center items-center gap-6">
            <li id="browser" class="p-0.5 rounded-lg active:bg-slate-400 hover:bg-white hover:text-black"><a href="/">Browse</a></li>
            <li id="Order" class="p-0.5 rounded-lg active:bg-slate-400 hover:bg-white hover:text-black">
                <div
                    hx-get="{%url 'test:hx_menu_order'%}"
                    hx-trigger="update-menu-order from:body"
                    hx-swap="innerHTML"
                >
                    {% include 'order/menu_order.html' %}
                </div>
            </li>
            <li id="Contacts" class="p-0.5 rounded-lg active:bg-slate-400 hover:bg-white hover:text-black"><a href="/contacts/">Contacts</a></li>
        </ul>
        <div class="flex gap-4">
        {%if request.user.is_authenticated %}
            <a href="/logout/">Log Out</a>
        {%else%}
            <a href="/signup/" class="p-1 rounded-lg active:bg-slate-400 bg-green-700 hover:text-black">Sign Up</a>
            <a href="/login/" class="p-1 rounded-lg active:bg-slate-400 bg-cyan-700 hover:text-black">Login</a>
        {%endif%}
        </div>
    </nav>
</br>
</br>
    <div>
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

Capstone/resturant/core/templates/core/browser.html
{% extends 'core/base.html' %}


{% block title %}Welcome{% endblock %}

{% block content %}
<div>
    <div class="container mx-auto flex rounded-lg justify-center items-center gap-8 p-2 bg-slate-500 text-white">
        <a href="/" class="p-2 rounded-xl active:bg-slate-400 bg-gray-700 hover:text-black">All</a>
        {% for category in categories %}
            <div class="p-2 rounded-xl active:bg-slate-400 bg-gray-700 hover:text-black">
                <a href="/?category={{category.name}}">
                    <div>
                        <h2>{{category.name}}</h2>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
    <div class="grid grid-cols-3 gap-3 justify-center items-center text-center place-items-center mt-4">
        {% for meal in meals %}
            <div>
                <a>
                    <div>
                        <h2>{{meal.name}}</h2>
                        <h3>${{meal.price}}</h2>
                        <img src="{{meal.image.url}}" class="h-52 rounded-xl">
                        <a href="#" 
                        hx-get="{% url 'test:add_to_order' meal.id %}"
                        hx-target="#menu-order-button"
                        hx-swap="outerHTML"
                        >
                        Order This?
                        </a>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

Capstone/resturant/core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %}Welcome to Contacts{% endblock %}

{% block content %}
<h1>
    Hello my name is Dylan, I'm the creator of this website that your currently on <br>
    if you would like to contact me please email me.
</h1>
<h3>Email: Dsisson0505@gmail.com</h3>
{% endblock %}

Capstone/resturant/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Log In{% endblock %}

{% block content %}
<div>
    <h1>Login<h1>
    
    <form method="post" action=".">
        {% csrf_token %}

        {{ form.as_p}}
        <button>Submit</button>
    </form>
</div>
{% endblock %}

Capstone/resturant/core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<div>
    <h1>Sign Up<h1>
    
    <form method="post" action=".">
        {% csrf_token %}

        {{ form.as_p}}
        <button>Submit</button>
    </form>
</div>
{% endblock %}

Capstone/resturant/order/templates/order/menu_order.html
<a href="{% url 'test:order' %}" id="menu-order-button" class="relative">
    <span>Order {{order|length}}</span>
</a>

Capstone/resturant/order/templates/order/order.html
{% extends 'core/base.html' %}

{% block title %}Welcome to your Order{% endblock %}

{% block content %}
<div class="container mx-auto flex flex-col justify-center align-center bg-gray-300 rounded-xl">
    <h1 class="text-center">ORDER</h1>
    <div class="self-center">
        {%for item in order%}
            {%include 'order/partials/meal_item.html'%}
        {%endfor%}
    </div>
    <h2 class="text-center"> Total Cost: {{order.get_total_cost}}</h2>
</div>
{% endblock %}

Capstone/resturant/order/templates/order/partials/meal_item.html
<div class="flex mb-1" id="order-item-{{item.meal.id}}">
    <h1>-- {{item.meal.name}} -- ${{item.meal.price}}</h1>
    <div>
        <a href="#" class="ml-4 p-0.5 bg-gray-700 text-white rounded-xl hover:bg-gray-600"
        hx-get="{%url 'test:update_order' item.meal.id 'decrement'%}"
        hx-target="#order-item-{{item.meal.id}}"
        hx-swap="outerHTML"
        >Remove</a>
    </div>
</div>